name: fee_estimation_rest
description: A server app to provide required fees for broadcasting in different blockchain networks.
version: 0.0.1
homepage: https://fees.amitabha.xyz

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  args: ^2.0.0
  http: ^0.13.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
